services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    working_dir: /usr/src/app/backend
    volumes:
      - ./backend:/usr/src/app/backend
    command: listen --api-key "sk_test_place_stripe_api_key_here" --forward-to http://backend:3000/api/v1/payments/stripe/webhook
    depends_on:
      - backend